"""K8 — Error codes (owner O3). ErrorCode list v1, approved 2026-10-09, ADD-ONLY.

Codes may be added (PR with owner + one other); existing codes are never renamed or reused.
Codes are fixed identifiers: never put paths, document text or exception messages in them.
K1 validation codes (NON_FINITE, OUT_OF_RANGE, ...) are Issue codes — see contracts.config.
"""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    # --- Fonts (O1) ---
    BUNDLED_FONT_MISSING = "BUNDLED_FONT_MISSING"
    FONT_UNREADABLE = "FONT_UNREADABLE"
    BASE_IS_MONOSPACE = "BASE_IS_MONOSPACE"
    BASE_IS_ICON_FONT = "BASE_IS_ICON_FONT"
    PATCH_UNSUPPORTED = "PATCH_UNSUPPORTED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    INSTALL_FAILED = "INSTALL_FAILED"
    PREVIEW_UNAVAILABLE = "PREVIEW_UNAVAILABLE"

    # --- Apply / preflight (O2) ---
    APPLY_IN_PROGRESS = "APPLY_IN_PROGRESS"
    NOT_WRITABLE = "NOT_WRITABLE"
    NO_DISK_SPACE = "NO_DISK_SPACE"
    ADAPTER_UNAVAILABLE = "ADAPTER_UNAVAILABLE"
    TX_NOT_PENDING = "TX_NOT_PENDING"
    CONFIRM_STARTUP_TIMEOUT = "CONFIRM_STARTUP_TIMEOUT"
    CONFIRM_HEARTBEAT_LOST = "CONFIRM_HEARTBEAT_LOST"
    CONFIRM_TIMEOUT = "CONFIRM_TIMEOUT"
    SERVICE_UNREACHABLE = "SERVICE_UNREACHABLE"

    # --- Adapters (O4) ---
    ADAPTER_TIMEOUT = "ADAPTER_TIMEOUT"
    ADAPTER_COMMAND_FAILED = "ADAPTER_COMMAND_FAILED"  # external command exited non-zero
    ADAPTER_VERIFY_FAILED = "ADAPTER_VERIFY_FAILED"
    UNEXPECTED_ADAPTER_ERROR = "UNEXPECTED_ADAPTER_ERROR"
    CHECK_UNAVAILABLE = "CHECK_UNAVAILABLE"
    SCHEMA_MISSING = "SCHEMA_MISSING"
    QT6CT_NOT_IN_SESSION = "QT6CT_NOT_IN_SESSION"
    BROWSER_RUNNING = "BROWSER_RUNNING"
    PREFERENCES_UNREADABLE = "PREFERENCES_UNREADABLE"
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"

    # --- Safety (O4) ---
    BACKUP_MISSING = "BACKUP_MISSING"
    BACKUP_CORRUPT = "BACKUP_CORRUPT"
    CHANGED_DURING_APPLY = "CHANGED_DURING_APPLY"
    PLAN_CONFLICT = "PLAN_CONFLICT"
    LOCK_TIMEOUT = "LOCK_TIMEOUT"
    WRITE_NOT_DURABLE = "WRITE_NOT_DURABLE"
    REVERT_ITEM_FAILED = "REVERT_ITEM_FAILED"
    DRIFT_SKIPPED = "DRIFT_SKIPPED"
    KEYBIND_CONFLICT = "KEYBIND_CONFLICT"

    # --- Store (O3) ---
    STORE_BUSY = "STORE_BUSY"
    STORE_READ_ONLY = "STORE_READ_ONLY"
    MIGRATION_FAILED = "MIGRATION_FAILED"
    STORE_CORRUPT = "STORE_CORRUPT"
    STORE_IO_ERROR = "STORE_IO_ERROR"
    SCHEMA_UNSUPPORTED = "SCHEMA_UNSUPPORTED"
    PRESET_READ_ONLY = "PRESET_READ_ONLY"
    FONT_IDENTITY_CONFLICT = "FONT_IDENTITY_CONFLICT"
    FONT_IN_USE = "FONT_IN_USE"
    INTERRUPTED_BUILD = "INTERRUPTED_BUILD"
    SAMPLES_DISABLED = "SAMPLES_DISABLED"
    RECOVERY_OBLIGATIONS_REMAIN = "RECOVERY_OBLIGATIONS_REMAIN"

    # --- Tests (O3) ---
    SANDBOX_UNAVAILABLE = "SANDBOX_UNAVAILABLE"

    # --- Reader / capture (O2) ---
    NOTHING_SELECTED = "NOTHING_SELECTED"
    CLIPBOARD_EMPTY = "CLIPBOARD_EMPTY"
    SELECTION_UNAVAILABLE = "SELECTION_UNAVAILABLE"
    TOO_LARGE = "TOO_LARGE"

    # --- Extension / IPC (O4 + O2) ---
    APP_NOT_RUNNING = "APP_NOT_RUNNING"
    HOST_MISSING = "HOST_MISSING"
    BAD_MESSAGE = "BAD_MESSAGE"


class ScribeSenseError(Exception):
    """The only error type modules raise for expected failures (K3 rule 5, K8).

    Carries a code only — never a message with paths, text or other content.
    """

    def __init__(self, code: ErrorCode) -> None:
        super().__init__(code.value)
        self.code = code
